name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types: [opened, reopened, edited]
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy-step
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} >deployment-url.txt
          DEPLOYMENT_URL=$(cat deployment-url.txt)
          echo "::set-output name=deploymentUrl::$DEPLOYMENT_URL"  # Set DEPLOYMENT_URL as an output

  Add-Comment:
    runs-on: ubuntu-latest
    needs: Deploy-Preview
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Get PR Number
        id: pr-number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Comment URL to PR
        env:
          DEPLOYMENT_URL: ${{ needs.Deploy-Preview.outputs.deploymentUrl }}
        uses: actions/github-script@v6
        id: my-script
        with:
          script: |
            console.log('${{ env.PR_NUMBER }}', ${{ env.PR_NUMBER }},'${{ env.DEPLOYMENT_URL }}', ${{ env.DEPLOYMENT_URL }} , '${{ needs.Deploy-Preview.outputs.deploymentUrl }}', ${{ needs.Deploy-Preview.outputs.deploymentUrl }})
            github.rest.issues.createComment({
              issue_number: ${{ env.PR_NUMBER }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Deployed at ${{ env.DEPLOYMENT_URL }}"
            })
